# Retail Analytics Platform

## Notebook 03: Executive Dashboard Data Preparation

### Objective
Prepare aggregated datasets and KPI summaries for Power BI Executive Dashboard reporting.

### Outputs
- KPI Summary
- Product Summary
- Region Summary
- Customer Summary
- Monthly Sales Trend

### Author
Umesh Zure

### Tools
Python, Pandas, Power BI

In [5]:
# --------------------------------------------------
# Retail Analytics Platform
# Executive Dashboard Data Preparation
# --------------------------------------------------

import pandas as pd
import numpy as np

print("Libraries loaded successfully")

Libraries loaded successfully

In [12]:
# Load retail dataset

df = pd.read_csv("../data/sample_data/retail_sales.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 10
Columns: 7

,Order_ID,Order_Date,Store,Category,Product,Revenue,Quantity
0,1001,2026-01-10,Mumbai,Electronics,Laptop,85000,2
1,1002,2026-01-11,Pune,Furniture,Desk,25000,5
2,1003,2026-01-12,Delhi,Electronics,Mobile,65000,10
3,1004,2026-01-13,Bangalore,Office Supplies,Printer,15000,3
4,1005,2026-01-14,Mumbai,Furniture,Chair,12000,8

In [9]:
import os

for root, dirs, files in os.walk("../data"):
    print("\nFolder:", root)
    
    for file in files:
        print("   ", file)

Folder: ../data

Folder: ../data\processed

Folder: ../data\raw

Folder: ../data\sample_data
    retail_sales.csv

In [13]:
print("Dataset Information")
print("-" * 40)

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.info()

Dataset Information
----------------------------------------
Rows : 10
Columns : 7
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    10 non-null     int64
 1   Order_Date  10 non-null     str
 2   Store       10 non-null     str
 3   Category    10 non-null     str
 4   Product     10 non-null     str
 5   Revenue     10 non-null     int64
 6   Quantity    10 non-null     int64
dtypes: int64(3), str(4)
memory usage: 1.0 KB

In [14]:
# Executive KPI Summary

kpi_summary = pd.DataFrame({

    "Metric": [
        "Total Revenue",
        "Total Orders",
        "Total Products",
        "Total Categories",
        "Total Stores"
    ],

    "Value": [
        df["Revenue"].sum(),
        df["Order_ID"].nunique(),
        df["Product"].nunique(),
        df["Category"].nunique(),
        df["Store"].nunique()
    ]
})

kpi_summary

             Metric   Value
0     Total Revenue  296000
1      Total Orders      10
2    Total Products      10
3  Total Categories       3
4      Total Stores       4

In [15]:
product_summary = (
    df.groupby("Product")["Revenue"]
    .sum()
    .reset_index()
    .sort_values("Revenue", ascending=False)
)

product_summary.head()

   Product  Revenue
4   Laptop    85000
5   Mobile    65000
6  Monitor    35000
9   Tablet    28000
2     Desk    25000

In [16]:
# Revenue by Category

category_summary = (
    df.groupby("Category")["Revenue"]
      .sum()
      .reset_index()
      .sort_values("Revenue", ascending=False)
)

category_summary

          Category  Revenue
0      Electronics   217000
1        Furniture    59000
2  Office Supplies    20000

In [17]:
# Revenue by Store

store_summary = (
    df.groupby("Store")["Revenue"]
      .sum()
      .reset_index()
      .sort_values("Revenue", ascending=False)
)

store_summary

       Store  Revenue
1      Delhi   122000
2     Mumbai   101000
0  Bangalore    43000
3       Pune    30000

In [18]:
# Convert Order Date

df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [19]:
monthly_sales = (
    df.groupby(df["Order_Date"].dt.to_period("M"))["Revenue"]
      .sum()
      .reset_index()
)

monthly_sales

  Order_Date  Revenue
0    2026-01   296000

In [20]:
# Export files for Power BI

kpi_summary.to_csv(
    "../data/processed/kpi_summary.csv",
    index=False
)

product_summary.to_csv(
    "../data/processed/product_summary.csv",
    index=False
)

category_summary.to_csv(
    "../data/processed/category_summary.csv",
    index=False
)

store_summary.to_csv(
    "../data/processed/store_summary.csv",
    index=False
)

monthly_sales.to_csv(
    "../data/processed/monthly_sales.csv",
    index=False
)

print("Dashboard datasets exported successfully")

Dashboard datasets exported successfully

In [21]:
import os

files = os.listdir("../data/processed")

for file in files:
    print(file)

category_summary.csv
kpi_summary.csv
monthly_sales.csv
product_summary.csv
store_summary.csv